LearningApp/Controllers/QuestionaireController.cs
using Microsoft.AspNet.Identity;
using ServiceLayer.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LearningApp.Controllers
{
    public class QuestionaireController : Controller
    {
        private readonly IQuestionaireService questionaireService;
        public QuestionaireController(IQuestionaireService questionaireService)
        {
            this.questionaireService = questionaireService;
        }

        [HttpGet]
        public ActionResult FillQuestionaire()
        {
            var questionaireViewModel = questionaireService.ReadQuestionaireFromJson();
            return View(questionaireViewModel);
        }

        [HttpPost]
        public ActionResult FillQuestionaire(int[] answers)
        {
            var userId = System.Web.HttpContext.Current.User.Identity.GetUserId();
            var questionaireResult = questionaireService.InterpretateResults(answers, userId);
            return View("QuestionaireResults", questionaireResult.ComputedLearningStyle);
        }

    }
}

LearningApp/Views/Questionaire/FillQuestionaire.cshtml
@using ServiceLayer.Services
@using DataAccessLayer.Models.Enums;
@model QuestionaireViewModel
@{
    ViewBag.Title = "FillQuestionaire";
}
<div class="page-header">
    <h2><small>Formularz wyboru najlepszego stylu nauczania</small></h2>
</div>
@if (Model != null)
{
    using (Html.BeginForm("FillQuestionaire", "Questionaire", FormMethod.Post))
    {
        var enumerator = 0;
        var listing = 1;
        foreach (var question in Model.Questionaire)
        {
            <b>@(listing). @question.Question</b>


            foreach (var answer in question.Answers)
            {
                <div class="radio">
                    <label><input type="radio" name="answers[@enumerator]" value="@((int)answer.AnswerType)">@answer.Answer</label>
                </div>
            }
            enumerator++;
            listing++;
        }
        <div>
            <input class="btn btn-sm btn-primary" type="submit" value="Zapisz odpowiedzi" />
        </div>
    };

}

LearningApp/Views/Questionaire/QuestionaireResults.cshtml
@using DataAccessLayer.Models.Enums
@model LearningTypes
@{
    ViewBag.Title = "QuestionaireResults";
}

<div class="page-header">
    <h2><small>Wyniki przeprowadzonej ankiety o najlepszym stylu nauczania</small></h2>
</div>
<div style="text-align:center;">
    <h3>Wybrany dla ciebie styl nauki to : @(Model) </h3>
    @Html.ActionLink("Powrót do menu głównego", "Index","Home", null, new { @class = "btn btn-sm btn-success" })
</div>