LearningApp/Controllers/LessonController.cs
using DataAccessLayer.Models;
using DataAccessLayer.Models.Enums;
using LearningApp.Filters;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using ServiceLayer.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LearningApp.Controllers
{
    [QuestionaryAuthorizeFilter]
    public class LessonController : BaseController
    {
        private ILessonService lessonService;
        private IQuestionaireService questionaireService;

        public LessonController(ILessonService lessonService, IQuestionaireService questionaireService)
        {
            this.lessonService = lessonService;
            this.questionaireService = questionaireService;
        }

        [HttpGet]
        public ActionResult Index()
        {
            var userId = System.Web.HttpContext.Current.User.Identity.GetUserId();
            var vm = lessonService.GetUserLessons(userId);
            return View(vm);
        }

        [HttpGet]
        public ActionResult LessonsPanel()
        {
            var vm = lessonService.GetAllLessons();
            return View(vm);
        }

        [HttpGet]
        public ActionResult LessonLearn(long id)
        {
            var userId = System.Web.HttpContext.Current.User.Identity.GetUserId();
            var learnType = questionaireService.GetUserLearningType(userId);
            var vm = lessonService.GetDataForOrderedLessonPreview(id, learnType);
            return View(vm);
        }

        [HttpGet]
        public ActionResult CreateLesson()
        {
            return View();
        }

        [HttpPost]
        public ActionResult CreateLesson(LessonViewModel vm)
        {
            var userId = System.Web.HttpContext.Current.User.Identity.GetUserId();
            if (ModelState.IsValid)
            {
                lessonService.CreateLesson(vm, userId);
            }
            else
            {
                return View(vm);
            }

            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Edit(long id)
        {
            var vm = lessonService.GetLesson(id);
            return View("EditLesson", vm);
        }

        [HttpPost]
        public ActionResult Edit(LessonViewModel vm)
        {
            if (ModelState.IsValid)
            {
                lessonService.UpdateLesson(vm);
            }
            else
            {
                return View("EditLesson", vm);
            }

            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult ConfirmDelete(long id)
        {
            return View(id);
        }

        [HttpPost]
        public ActionResult Delete(long id)
        {
            lessonService.DeleteLesson(id);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult PreviewLessonContent(long id, bool? ordered, LearningTypes? type)
        {
            LessonContentPreviewViewModel vm = new LessonContentPreviewViewModel();
            if(ordered==true)
            {
                vm = lessonService.GetDataForOrderedLessonPreview(id, type);
            }
            else
            {
                vm = lessonService.GetDataForLessonPreview(id);
            }
            
            return PartialView("PreviewLesson", vm);
        }

        [HttpGet]
        public ActionResult CreateLessonElement(long? id)
        {
            if(id!=null)
            {
                return PartialView(new LessonElementViewModel() { LessonId=id.Value,});
            }
            return PartialView();
        }

        [HttpPost]
        public ActionResult CreateLessonElement(LessonElementViewModel vm)
        {
            Object response = null;
            if (ModelState.IsValid)
            {
                var result = lessonService.CreateLessonElement(vm);
                response = result == true ?
                    new { ResponseType = JsonResponseType.Success, AdditionalData = "" } :
                    new { ResponseType = JsonResponseType.Error, AdditionalData = "Error occured during lesson element creation." };
            }
            else
            {
                return View(vm);
            }

            return Json(response);
        }

        [HttpGet]
        public ActionResult AddExistingLessonElement(long lessonId)
        {
            return View(lessonId);
        }

        [HttpPost]
        public ActionResult AddExistingLessonElement(int lessonId, int lessonElementId)
        {
            bool result = this.lessonService.AddExistingLessonElementToLesson(lessonId, lessonElementId);
            object response = result == true ?
                    new { ResponseType = JsonResponseType.Success, AdditionalData = "" } :
                    new { ResponseType = JsonResponseType.Error, AdditionalData = "Error occured during lesson element deletion." };
            return Json(response);
        }

        [HttpPost]
        public ActionResult RemoveLessonElement(long lessonId, long lessonElementId)
        {
            bool result = lessonService.RemoveLessonElement(lessonId, lessonElementId);
            object response = result == true ?
                    new { ResponseType = JsonResponseType.Success, AdditionalData = "" } :
                    new { ResponseType = JsonResponseType.Error, AdditionalData = "Error occured during lesson element deletion." };
            return Json(response);
        }

        [HttpGet]
        public ActionResult ModifyLessonContent()
        {
            return View();
        }


        public ActionResult GetLessonsForAutoComplete()
        {
            var data = lessonService.GetAllLessonsForComboBox();
            return Json(data.ToList(), JsonRequestBehavior.AllowGet);
        }

        public ActionResult GetLessonsElementsForAutoComplete()
        {
            var data = lessonService.GetAllLessonsElementsForComboBox();
            return Json(data.ToList(), JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult LessonOrderItems()
        {
            return View();
        }
        
        [HttpPost]
        public ActionResult ChangeLessonElementOrder(long lessonId, long lessonElementId, bool increment, LearningTypes type)
        {
            bool result = lessonService.ChangeLessonElementOrder(lessonId, lessonElementId, increment, type);
            object response = result == true ?
                    new { ResponseType = JsonResponseType.Success, AdditionalData = "Lesson element order changed" } :
                    new { ResponseType = JsonResponseType.Error, AdditionalData = "Error occured during lesson element deletion." };
            return Json(response);
        }

        [HttpPost]
        public ActionResult PreviewSingleLessonElement(int lessonElementId)
        {
            LessonElementViewModel vm = this.lessonService.GetLessonElement(lessonElementId);
            return View(vm);
        }
    }
}

LearningApp/Controllers/MediaController.cs
using ServiceLayer.Services;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LearningApp.Controllers
{
    public class MediaController : Controller
    {
        private readonly IMediaService mediaService;

        public MediaController(IMediaService mediaService)
        {
            this.mediaService = mediaService;
        }
        
        public string RenderImage(long id)
        {
            var file = this.mediaService.GetFileAsByteArray(id);
            var base64 = Convert.ToBase64String(file);
            var imgSrc = String.Format("data:image/gif;base64,{0}", base64);
            var imageTemplate = string.Format("<img src='{0}' />", imgSrc);

            return imageTemplate;
        }

        public ActionResult GetAudioStream(long id)
        {
            var byteArray = this.mediaService.GetFileAsByteArray(id);
            var memoryStream = new MemoryStream(byteArray);

            return new FileStreamResult(memoryStream, "audio/mp3"); ;
        }

        public ActionResult GetVideoStream(long id)
        {
            var byteArray = this.mediaService.GetFileAsByteArray(id);
            var memoryStream = new MemoryStream(byteArray);

            return new FileStreamResult(memoryStream, "video/mp4"); ;
        }
    }
}

LearningApp/Views/Lesson/AddExistingLessonElement.cshtml
@{
    Layout = null;
}
@model long
@using DataAccessLayer.Models;

@using (Html.BeginForm("AddExistingLessonElement", "Lesson", FormMethod.Post, new { lessonId = Model }))
{
    @Html.Hidden("lessonId", Model, new { id = "LessonIdContainer" })
    @Html.AntiForgeryToken()
    <div class="panel-group">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h4 class="panel-title">
                    <a data-toggle="collapse" href="#collapse_lessonElementCreateExisting">Dodawanie istniejącego elementu lekcji</a>
                </h4>
            </div>
            <div id="collapse_lessonElementCreateExisting" class="panel-collapse collapse">
                <div class="panel-body">
                    <div class="form-horizontal">
                        <div class="form-group">
                            @Html.Label("Identyfikator", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                <input type="text" class="form-control" name="LessonsElementsList" id="ExistingLessonElementSearch" data-provide="typeahead" placeholder="Wybierz element..." autocomplete="off" />
                            </div>
                        </div>
                        <div id="ExistingLessonElementPreviewContainer"></div>
                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="button" id="CreateExistingLessonElement" value="Dodaj" class="btn btn-default" />
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

}
<script>
    $(document).ready(function () {

    });
</script>

LearningApp/Views/Lesson/ConfirmDelete.cshtml
@model long
@{
    ViewBag.Title = "ConfirmDelete";
}

<div class="page-header">
    <h2><small>Panel usuwania lekcji</small></h2>
</div>

<div class="col-md-12" style="text-align:center;" >
    @using (Html.BeginForm("Delete","Lesson", FormMethod.Post))
    {
        @Html.Hidden("id",Model)
        <p>Lekcja wraz z zawartością zostanie usunięta. Czy aby na pewno chcesz kontynuować?</p>
        <p>
            @Html.ActionLink("<- Powrót", "Index", null, new { @class = "btn btn-sm btn-primary" })  
            <input type="submit" class="btn btn-sm btn-danger" value="Usuń"/>
        </p>

    }
</div>

LearningApp/Views/Lesson/CreateLesson.cshtml
@model ServiceLayer.Services.LessonViewModel

<div class="page-header">
    <h2><small>Panel tworzenia lekcji</small></h2>
</div>
@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Utwórz" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("<- Powrót", "Index", null,new { @class="btn btn-sm btn-primary"})
</div>

LearningApp/Views/Lesson/CreateLessonElement.cshtml
@{
    Layout = null;
}
@model ServiceLayer.Services.LessonElementViewModel
@using DataAccessLayer.Models;

@using (Html.BeginForm("CreateLessonElement", "Lesson", FormMethod.Post, new { @enctype = "multipart/form-data", id="LessonELementCreationForm" }))
{
    @Html.AntiForgeryToken()
    <div class="panel-group">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h4 class="panel-title">
                    <a data-toggle="collapse" href="#collapse_lessonElementCreate">Tworzenie nowego elementu lekcji</a>
                </h4>
            </div>
            <div id="collapse_lessonElementCreate" class="panel-collapse collapse">
                <div class="panel-body">
                    <div class="form-horizontal">
                    
                        @Html.ValidationSummary(true, "", new { @class = "text-danger", enctype = "multipart/form-data" })
                        @Html.HiddenFor(q=>q.LessonId)
                        <div class="form-group">
                            @Html.Label("Typ elementu", new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EnumDropDownListFor(q => q.LessonElementType, new { id = "LessonElementType", @class = "form-control" })
                            </div>
                        </div>
                        @*@Html.HiddenFor(q=>q.LessonElementType, new { id= "LessonElementType" })*@
                        <div class="form-group">
                            @Html.Label("Identyfikator", new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Identifier, new { htmlAttributes = new { @class = "form-control" } })
                            </div>
                        </div>
                        <div class="form-group modal-element for_imageType for_audioType for_videoType">
                            @Html.Label("Plik", new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                <input type="file" class="form-control" name="File" id="File"/>
                            </div>
                        </div>

                        <div class="form-group modal-element for-textType">
                            @Html.Label("Zawartość lekcji", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                <textarea id="Content" class="form-control" name="TextContent" placeholder="Dodaj zawartość" style="width:100%;"></textarea>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="button" id="CreateLessonElement" value="Utwórz" class="btn btn-default" />
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

}


<script type="text/javascript">
    $('#Content').wysihtml5({
        toolbar: {
            "blockquote": false,
            "font-styles": true, //Font styling, e.g. h1, h2, etc.
            "emphasis": true, //Italics, bold, etc.
            "lists": true, //(Un)ordered lists, e.g. Bullets, Numbers.
            "html": false, //Button which allows you to edit the generated HTML.
            "link": false, //Button to insert a link.
            "image": false, //Button to insert an image.
            "color": true //Button to change color of font
            }
    });
</script>
<style>
    ul.wysihtml5-toolbar {
    list-style-type: none;
    display: inline-flex;
    margin-left: -40px;
}
</style>

LearningApp/Views/Lesson/EditLesson.cshtml
@model ServiceLayer.Services.LessonViewModel

<div class="page-header">
    <h2><small>Panel edycji lekcji</small></h2>
</div>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Zapisz" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("<- Powrót", "Index", null, new { @class = "btn btn-sm btn-primary" })
</div>

LearningApp/Views/Lesson/LessonLearn.cshtml
@model ServiceLayer.Services.LessonContentPreviewViewModel
@using DataAccessLayer.Models
@{
    ViewBag.Title = "PreviewLesson";
}

<div class="page-header">
    <h2><small>Panel nauki</small></h2>
</div>
@Html.HiddenFor(q => q.Id, new { id = "LessonId" })
<div class="panel panel-default">
    <div class="panel-heading">Zawartość lekcji</div>
    <div class="panel-body">
        <div>
            <div>
                <dl class="dl-horizontal">
                    <dt>
                        @Html.DisplayName("Nazwa")
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Name)
                    </dd>

                    <dt>
                        @Html.DisplayName("Opis")
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Description)
                    </dd>

                    <dt>
                        @Html.DisplayName("Twórca")
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.CreatorFullName)
                    </dd>

                </dl>
            </div>
            <div>
                @foreach (var lessonElement in Model.LessonElements)
                {
                    var centerAttr = (lessonElement.LessonElementType != LessonElementType.Text) ? "center-media" : "";
                    <div class="item-lesson lesson-element-container @(centerAttr)" lesson-order="@(lessonElement.CurrentOrder)" lesson-id="@(Model.Id)" lesson-element-id="@(lessonElement.Id)">
                        @switch (lessonElement.LessonElementType)
                        {
                            case LessonElementType.Text:
                                @Html.Raw(@lessonElement.TextContent)
                                break;
                            case LessonElementType.Image:
                                @Html.Raw(@Html.Action("RenderImage", "Media", new { id = lessonElement.FileId }))
                                break;
                            case LessonElementType.Audio:
                                @Html.Raw("<audio controls><source src='/Media/GetAudioStream/" + lessonElement.FileId + "' type='audio/mp3' /></audio>")
                                break;
                            case LessonElementType.Video:
                                @Html.Raw("<video width='320' height='240' controls><source src='/Media/GetVideoStream/" + lessonElement.FileId + "'/></video>")
                                break;
                        }
                        @*<span class="glyphicon glyphicon-arrow-up preview-lesson-up-icon" aria-hidden="true"></span>
                            <span class="glyphicon glyphicon-arrow-down preview-lesson-down-icon" aria-hidden="true"></span>*@
                    </div>
                }
            </div>
        </div>
    </div>
</div>

<style>
    .center-media {
        text-align: center;
    }
</style>

LearningApp/Views/Lesson/LessonOrderItems.cshtml
@using ServiceLayer.Services
@model LessonOrderViewModel
@{
    ViewBag.Title = "LessonOrderItems";
}

<div class="page-header">
    <h2><small>Panel zmiany kolejności elementów lekcji</small></h2>
</div>
<div id="AvailableLessonsCombobox" class="form-horizontal">
    <div class="well panel-primary well-sm">Wpisz nazwę lekcji aby załadować dane.</div>
    <div class="form-group">
        @Html.Label("Nazwa lekcji", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <input type="text" class="form-control" name="LessonsList" id="LessonsSearch" data-provide="typeahead" placeholder="Select lesson..." autocomplete="off" />
        </div>
    </div>
    <div class="form-group">
        @Html.Label("Typ nauczania", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
          @Html.EnumDropDownListFor(q=>q.LearningTypes, new { @class= "form-control", id="LearningTypeCombo" })
        </div>
    </div>
</div>
<div id="LessonPreviewContainer"></div>
<script>
    $(document).on("click", ".preview-lesson-up-icon", function () {
        var clickedElement = $(this).parent();
        var lessonType = $("#LearningTypeCombo").val();
        var lessonId = clickedElement.attr("lesson-id");
        var lessonElementId = clickedElement.attr("lesson-element-id");
        var increment = true;
        $.post('@Url.Action("ChangeLessonElementOrder", "Lesson")' + '?lessonId=' + lessonId + "&lessonElementId=" + lessonElementId + "&increment=" + increment + "&type=" + lessonType, null, function (data) {

            $("#LessonsSearch").trigger('change');
            notificationScope.CreateNotification('Successfuly created lesson element.', 'glyphicon glyphicon-ok', 'Lesson element creation -', 'success');
        });
    });
    $(document).on("click", ".preview-lesson-down-icon", function () {
        var clickedElement = $(this).parent();
        var lessonType = $("#LearningTypeCombo").val();
        var lessonId = clickedElement.attr("lesson-id");
        var lessonElementId = clickedElement.attr("lesson-element-id");
        var increment = false;
        $.post('@Url.Action("ChangeLessonElementOrder", "Lesson")' + '?lessonId=' + lessonId + "&lessonElementId=" + lessonElementId + "&increment=" + increment + "&type=" + lessonType, null, function (data) {

            $("#LessonsSearch").trigger('change');
            notificationScope.CreateNotification('Successfuly created lesson element.', 'glyphicon glyphicon-ok', 'Lesson element creation -', 'success');
        });
    });
    $(".item-lesson").hover(function () {

    }, function () {

    });
    $(document).ready(function () {
 
        $("#LessonsSearch").typeahead({
            source: function (query, process) {
                var lessons = [];
                map = {};

                // This is going to make an HTTP post request to the controller
                return $.post('/Lesson/GetLessonsForAutoComplete', { query: query }, function (data) {

                    // Loop through and push to the array
                    $.each(data, function (i, iterator) {
                        map[iterator.Name] = iterator;
                        lessons.push(iterator.Name);
                    });

                    // Process the details
                    process(lessons);

                });
            },
            updater: function (item) {
                var Id = map[item].Id;

                // Set the text to our selected id
                $("#LessonsSearch").attr("value", Id);

                return item;
            }
        });
       

        $(document).on("change", "#LessonsSearch", LoadModifyPanels).triggerHandler('change');
        $(document).on("change", "#LearningTypeCombo", LoadModifyPanels).triggerHandler('change');
        $(".item-lesson").hover(function(){
        
        }, function(){
        
        });
        
        function LoadModifyPanels() {

            var lessonId = $("#LessonsSearch").attr('value');
            var previewLessonView;
            var createLessonElementView;
            var lessonType = $("#LearningTypeCombo").val();
            if (lessonId != null && lessonId != 'undefined') {
                $.get('@Url.Action("PreviewLessonContent", "Lesson")' + '?id=' + lessonId + "&ordered=true" + "&type=" + lessonType, null, function (data) {

                    $("#LessonPreviewContainer").html(data);
                });

            }
        }
    });
</script>

LearningApp/Views/Lesson/LessonsPanel.cshtml
@model IEnumerable<ServiceLayer.Services.LessonViewModel>

<div class="page-header">
    <h2><small>Lista dostępnych lekcji</small></h2>
</div>

<table class="table">
    <tr class="table-header-row">
        <th>
            <h4><small>@Html.DisplayName("Nazwa")</small></h4>
        </th>
        <th>
            <h4>
                <small>
                    @Html.DisplayName("Opis")
                </small>
            </h4>
        </th>
        <th>
            <h4><small>@Html.DisplayName("Twórca")</small></h4>
        </th>
        <th></th>
    </tr>
    @if (Model.Any())
    {
        foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CreatorFullName)
                </td>
                <td>
                    @Html.ActionLink("Otwórz lekcję", "LessonLearn", new { id = item.Id }, new { @class = "btn-xs btn btn-primary" })
                </td>
            </tr>
        }
    }


</table>

LearningApp/Views/Lesson/PreviewLesson.cshtml
@model ServiceLayer.Services.LessonContentPreviewViewModel
@using DataAccessLayer.Models
@{
    ViewBag.Title = "PreviewLesson";
    Layout = null;
}
@Html.HiddenFor(q => q.Id, new { id = "LessonId" })
<div class="panel panel-default">
    <div class="panel-heading">Podgląd lekcji</div>
    <div class="panel-body">
        <div>
            <div>
                <dl class="dl-horizontal">
                    <dt>
                        @Html.DisplayName("Nazwa")
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Name)
                    </dd>

                    <dt>
                        @Html.DisplayName("Opis")
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Description)
                    </dd>

                    <dt>
                        @Html.DisplayName("Twórca")
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.CreatorFullName)
                    </dd>

                </dl>
            </div>
            <div>
                @foreach (var lessonElement in Model.LessonElements)
                {
                    var centerAttr = (lessonElement.LessonElementType != LessonElementType.Text) ? "center-media" : "";
                    <div class="item-lesson lesson-element-container @(centerAttr)" lesson-order="@(lessonElement.CurrentOrder)" lesson-id="@(Model.Id)" lesson-element-id="@(lessonElement.Id)">      
                        @switch (lessonElement.LessonElementType)
                        {
                            case LessonElementType.Text:
                                @Html.Raw(@lessonElement.TextContent)
                                break;
                            case LessonElementType.Image:
                                @Html.Raw(@Html.Action("RenderImage", "Media", new { id = lessonElement.FileId }))
                                break;
                            case LessonElementType.Audio:
                                @Html.Raw("<audio controls><source src='/Media/GetAudioStream/" + lessonElement.FileId+ "' type='audio/mp3' /></audio>")
                                break;
                            case LessonElementType.Video:
                                @Html.Raw("<video width='320' height='240' controls><source src='/Media/GetVideoStream/" + lessonElement.FileId + "'/></video>")
                                break;
                        }
                        <span class="glyphicon glyphicon-arrow-up preview-lesson-up-icon" aria-hidden="true"></span>
                        <span class="glyphicon glyphicon-arrow-down preview-lesson-down-icon" aria-hidden="true"></span>
                    </div>
                }

            </div>
        </div>
    </div>
</div>
<style>
    .item-lesson :hover {
    }

    .lesson-element-container {
        position: relative;
        margin-right: 40px;
    }

    .center-media
    {
        text-align:center;
    }
    .preview-lesson-up-icon {
        position: absolute;
        top: 0px;
        right: -15px;
    }

    .preview-lesson-down-icon {
        position: absolute;
        top: 0px;
        right: -40px;
    }


    .preview-lesson-up-icon:hover {
        cursor: pointer;
    }

    .preview-lesson-down-icon:hover {
        cursor: pointer;
    }
</style>

LearningApp/Views/Lesson/PreviewSingleLessonElement.cshtml
@using ServiceLayer.Services;
@using DataAccessLayer.Models;
@{ 
    Layout = null;
}
@model LessonElementViewModel

@{var centerAttr = (Model.LessonElementType != LessonElementType.Text) ? "center-media" : "";
    <div class="item-lesson lesson-element-container @(centerAttr)" lesson-order="@(Model.CurrentOrder)" lesson-id="@(Model.Id)" lesson-element-id="@(Model.LessonId)">
        @switch (Model.LessonElementType)
        {
            case LessonElementType.Text:
                @Html.Raw(@Model.TextContent)
                break;
            case LessonElementType.Image:
                @Html.Raw(@Html.Action("RenderImage", "Media", new { id = Model.FileId }))
                break;
            case LessonElementType.Audio:
                @Html.Raw("<audio controls><source src='/Media/GetAudioStream/" + Model.FileId + "' type='audio/mp3' /></audio>")
                break;
            case LessonElementType.Video:
                @Html.Raw("<video width='320' height='240' controls><source src='/Media/GetVideoStream/" + Model.FileId + "'/></video>")
                break;
        }
        @*<span class="glyphicon glyphicon-arrow-up preview-lesson-up-icon" aria-hidden="true"></span>
            <span class="glyphicon glyphicon-arrow-down preview-lesson-down-icon" aria-hidden="true"></span>*@
    </div>
}
<style>
    .center-media {
        text-align: center;
    }
</style>